baseURL = "https://payloads.online/"
languageCode = "zh-cn"
title = "倾旋的博客"
copyright = "倾旋 All rights reserved"
author = "倾旋"
# theme = "ink-free"
theme = "hugo-paper"
test = "Hello"
# [taxonomies]
#   tag = "tags"
#   category = "categories"
#   course = "courses"

[params]
  email = "rvn0xsy@gmail.com"
  avatar = "/avatar.jpeg"
  author = "倾旋"
  description = "现阶段在进行有效性验证/攻击模拟相关的安全研究工作，我的博客会记录一些我的学习过程和部分安全技术研究成果。"
  subtitle = "现阶段在进行有效性验证/攻击模拟相关的安全研究工作，我的博客会记录一些我的学习过程和部分安全技术研究成果。"
  toc = "floating"
  wpm = 250
  maxTags = 7
	mode = "dark"

[params.giscus]
  repo = 'Rvn0xsy/rvn0xsy.github.io'                 # see https://giscus.app for more details
  repoId = 'MDEwOlJlcG9zaXRvcnk0MDEyMzI3MTY='
  category = 'General'
  categoryId = 'DIC_kwDOF-pTTM4CRDk_'
  mapping = 'title'
  theme = 'light'
  lang = 'zh-CN'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章列表"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 3
  [[menu.main]]
    identifier = "projects"
    name = "开源项目"
    url = "/projects"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about"
    weight = 5
  [[menu.main]]
    identifier = "links"
    name = "友情链接"
    url = "/links/"
    weight = 6
  [[menu.main]]
    identifier = "message"
    name = "留言"
    url = "/message"
    weight = 7
  [[menu.main]]
    identifier = "sponsor"
    name = "赞助"
    url = "/sponsor"
    weight = 8

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rvn0xsy/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Wechat"
icon = "message-circle"
url = "/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rvn0xsy/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"



[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

[services.instagram]
  disableInlineCSS = true

[services.x]
  disableInlineCSS = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true